#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")/.."
# Prefer a full Xcode toolchain. Some CLT SDKs expose macros without shipping their plugins.
if [[ -z "${DEVELOPER_DIR:-}" ]]; then
  for candidate in /Applications/Xcode.app /Applications/Xcode*.app /Volumes/*/Applications/Xcode*.app; do
    [[ -d "$candidate/Contents/Developer/Toolchains/XcodeDefault.xctoolchain" ]] || continue
    export DEVELOPER_DIR="$candidate/Contents/Developer"
    break
  done
fi
VERSION="${VERSION:-0.3.0}"
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo 'VERSION must be x.y.z' >&2; exit 1; }
# Sign in a temporary directory: iCloud/File Provider can attach Finder metadata
# to Desktop bundles between xattr and codesign.
BUILD_STAGE="${BUILD_STAGE:-$(mktemp -d "${TMPDIR:-/tmp}/easy-vphone-build.XXXXXX")}"
APP="$BUILD_STAGE/easy-vphone.app"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources" .build
xcrun swiftc -swift-version 5 -parse-as-library -O -target arm64-apple-macosx15.0 -module-cache-path "$PWD/.build" Sources/*.swift -o "$APP/Contents/MacOS/easy-vphone" -framework SwiftUI -framework AppKit
xcrun clang -O2 -Wall -Wextra Helpers/terminal.c -o "$APP/Contents/Resources/easy-vphone-terminal"
cp -R Resources/. "$APP/Contents/Resources/"
# Exclude Python bytecode generated by local tests.
find "$APP/Contents/Resources" -name '*.pyc' -delete
find "$APP/Contents/Resources" -type d -name __pycache__ -empty -delete
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>CFBundleIdentifier</key><string>io.github.easy-vphone</string>
<key>CFBundleName</key><string>easy-vphone</string>
<key>CFBundleExecutable</key><string>easy-vphone</string>
<key>CFBundleIconFile</key><string>AppIcon</string>
<key>CFBundlePackageType</key><string>APPL</string>
<key>CFBundleShortVersionString</key><string>$VERSION</string>
<key>CFBundleVersion</key><string>$VERSION</string>
<key>LSMinimumSystemVersion</key><string>15.0</string>
<key>CFBundleDevelopmentRegion</key><string>en</string>
<key>CFBundleLocalizations</key><array><string>tr</string><string>en</string><string>de</string><string>fr</string><string>es</string><string>it</string><string>pt</string><string>ru</string><string>ja</string><string>zh-Hans</string></array>
<key>NSHighResolutionCapable</key><true/>
</dict></plist>
PLIST
xattr -cr "$APP"
if [[ -n "${SIGN_IDENTITY:-}" ]]; then
  codesign --force --options runtime --timestamp --sign "$SIGN_IDENTITY" "$APP/Contents/Resources/easy-vphone-terminal"
  codesign --force --options runtime --timestamp --sign "$SIGN_IDENTITY" "$APP"
else
  codesign --force --sign - "$APP/Contents/Resources/easy-vphone-terminal"
  codesign --force --sign - "$APP"
fi
codesign --verify --deep --strict "$APP"
mkdir -p dist
/usr/bin/ditto --norsrc "$APP" "$PWD/dist/easy-vphone.app"
echo "$PWD/dist/easy-vphone.app"
